<?php
$payment = Payment_Manager::getInstance();
$idPage = $this->social->getIdPage();
$trialPayment = $payment->getHandlerByCode(Payment_Item_Trial::CODE);
?>

<?php if ($payment->isExistHandlerByCode(Payment_Item_Campaign::CODE)): ?>
<?php $campaignPayment = $payment->getHandlerByCode(Payment_Item_Campaign::CODE); ?>
<?php if ($campaignPayment->isValid($idPage)): ?>
<span>Free trial: <?php echo floor(($payment->getTimeExpired($this->social->getIdPage(), Payment_Item_Campaign::CODE) - time()) / 86400); ?>
day(s) left</span>
<a href="http://media.younetco.com/contact-us" target="_blank">[ Upgrade
]</a>
<?php else:?>
<span>Free trial: expired</span>
<a href="http://media.younetco.com/contact-us" target="_blank">[ Upgrade
]</a>
<?php endif; ?>
<?php else:?>
<?php if (!$trialPayment->isValid($idPage)): ?>
<!--free trial-->
<span>Free trial: expired</span>
<a href="http://media.younetco.com/contact-us" target="_blank">[ Upgrade
]</a>
</div>
</div>
<div class="sm_message_panel">
<p class="header"><?php echo $this->translate('UNDER_CONSTRUCTION');?></p>
</div>
</div>
</body>
</html>
<?php exit(); ?>
<?php else:?>
<span>Free trial: <?php echo floor(($payment->getTimeExpired($this->social->getIdPage(), Payment_Item_Trial::CODE) - time()) / 86400); ?>
day(s) left</span>
<a href="http://media.younetco.com/contact-us" target="_blank">[ Upgrade
]</a>
<?php endif; ?>
<?php endif; ?>
